### ISSUE TITLE
Create fully workable Blogging platform with base functionalities

### ISSUE THREAD

**Issue by kadirpili** [SEFI2/makeit#2]
Functionalities such as:
- [x] 1. Rating system
- [x] 2. Posting blog
- [x] 3. Enable user to Upvote/Downvote/Favorite the blog
- [x] 4. Login/SignUp/Logout system
- [x] 5. Editor with convenient features for blogs 

And fix bugs for all of the above functionalities.
